services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workqueue
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    cap_add:
      - NET_ADMIN

  httpbin:
    image: mccutchen/go-httpbin
    ports:
      - "8080:8080"
